//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounttransaction
    {
        public int id { get; set; }
        public string title { get; set; }
        public int date { get; set; }
        public Nullable<int> fiscalyear_id { get; set; }
        public Nullable<int> account_id { get; set; }
        public int trasactiontype { get; set; }
        public string identifier { get; set; }
        public string description { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<int> sync_id { get; set; }
        public int mode { get; set; }
        public decimal amount { get; set; }
        public int forgin_id { get; set; }
    
        public virtual account account { get; set; }
        public virtual fiscalyear fiscalyear { get; set; }
    }
}
