//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class manufactureditem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public manufactureditem()
        {
            this.manufaturedsubitems = new HashSet<manufaturedsubitem>();
        }
    
        public int id { get; set; }
        public Nullable<int> menuitem_id { get; set; }
        public Nullable<int> date { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> admin_id { get; set; }
        public System.DateTime updated_at { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> sync_id { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string unit { get; set; }
        public string units { get; set; }
        public Nullable<int> purchaseitem_id { get; set; }
        public Nullable<int> fiscalyear_id { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual fiscalyear fiscalyear { get; set; }
        public virtual menuitem menuitem { get; set; }
        public virtual purchaseitem purchaseitem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<manufaturedsubitem> manufaturedsubitems { get; set; }
    }
}
