//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class manufacureduseitem
    {
        public int id { get; set; }
        public Nullable<int> manuitem_id { get; set; }
        public Nullable<int> manufacureditems_id { get; set; }
        public Nullable<int> purchaseitem_id { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string unit { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<int> sync_id { get; set; }
    
        public virtual manufactureditem manufactureditem { get; set; }
        public virtual menuitem menuitem { get; set; }
        public virtual purchaseitem purchaseitem { get; set; }
    }
}
