//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class party_ledgers
    {
        public int id { get; set; }
        public int date { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string billnumber { get; set; }
        public string type { get; set; }
        public System.DateTime updated_at { get; set; }
        public decimal due { get; set; }
        public decimal paid { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> sync_id { get; set; }
        public Nullable<decimal> returnamount { get; set; }
        public Nullable<int> party_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual party party { get; set; }
    }
}
