//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class party_payments
    {
        public int id { get; set; }
        public Nullable<int> purchaseinvoices_id { get; set; }
        public Nullable<decimal> paidamount { get; set; }
        public Nullable<int> date { get; set; }
        public Nullable<int> admin_id { get; set; }
        public Nullable<int> fiscalyear_id { get; set; }
        public string bankname { get; set; }
        public string transactionno { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> type { get; set; }
        public int mode { get; set; }
        public int action { get; set; }
        public Nullable<int> party_id { get; set; }
        public int paymentfor { get; set; }
    
        public virtual fiscalyear fiscalyear { get; set; }
        public virtual party party { get; set; }
        public virtual purchaseinvoice purchaseinvoice { get; set; }
    }
}
