//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shadow_accounts
    {
        public int id { get; set; }
        public int account_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string panno { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<decimal> totaltransaction { get; set; }
        public Nullable<decimal> currentdue { get; set; }
        public Nullable<decimal> currentadvance { get; set; }
        public string nationlity { get; set; }
        public Nullable<int> admin_id { get; set; }
        public System.DateTime updated_at { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> sync_id { get; set; }
        public int actiontype { get; set; }
        public int C_V { get; set; }
    }
}
