//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shadow_bills
    {
        public int id { get; set; }
        public int bill_id { get; set; }
        public string fiscal_year { get; set; }
        public int bill_no { get; set; }
        public string customer_name { get; set; }
        public string customer_address { get; set; }
        public string customer_phone { get; set; }
        public string cystomer_PAN { get; set; }
        public string bill_Date { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> taxble_amount { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public bool is_printetd { get; set; }
        public bool is_active { get; set; }
        public Nullable<System.TimeSpan> printed_time { get; set; }
        public string entered_by { get; set; }
        public string printed_by { get; set; }
        public Nullable<int> counter_id { get; set; }
        public Nullable<int> cusotomer_id { get; set; }
        public Nullable<int> admin_id { get; set; }
        public System.DateTime updated_at { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> sync_id { get; set; }
        public Nullable<int> date { get; set; }
        public int reprintamount { get; set; }
        public Nullable<int> fiscalyear_id { get; set; }
        public Nullable<decimal> paidamount { get; set; }
        public Nullable<decimal> nettotal { get; set; }
        public Nullable<decimal> grosstotal { get; set; }
        public decimal dueamount { get; set; }
        public decimal returnamount { get; set; }
        public int actiontype { get; set; }
        public int C_V { get; set; }
    }
}
