//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class shadow_purchaseinvoices
    {
        public int id { get; set; }
        public int purchaseinvoice_id { get; set; }
        public int billno { get; set; }
        public Nullable<int> transactionmode { get; set; }
        public Nullable<int> transationdate { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> due { get; set; }
        public Nullable<decimal> paid { get; set; }
        public int enabled { get; set; }
        public Nullable<int> fiscalyear_id { get; set; }
        public Nullable<decimal> grosstotal { get; set; }
        public Nullable<decimal> taxable { get; set; }
        public Nullable<int> admin_id { get; set; }
        public Nullable<int> parties_id { get; set; }
        public System.DateTime updated_at { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> sync_id { get; set; }
        public Nullable<decimal> nettotal { get; set; }
        public Nullable<int> date { get; set; }
        public int actiontype { get; set; }
        public int C_V { get; set; }
    }
}
