//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class wastagefood
    {
        public int id { get; set; }
        public Nullable<int> menuitem_id { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string unit { get; set; }
        public System.DateTime upadated_at { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> sync_id { get; set; }
        public Nullable<int> admins_id { get; set; }
        public Nullable<int> fiscalyear_id { get; set; }
        public Nullable<int> date { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual fiscalyear fiscalyear { get; set; }
        public virtual menuitem menuitem { get; set; }
    }
}
